import { ADMIN_ROUTES } from ".";
import { DASHBOARD_AUTH_ROUTES } from "../auth";
import { DASHBOARD_ROUTES } from "../main";

export const ADMIN_ACCESS_ROUTES = [
  // 1. Auth & Profile
  DASHBOARD_AUTH_ROUTES.MAIN,
  DASHBOARD_AUTH_ROUTES.PROFILE,

  // 2. Admin Staff Management
  ADMIN_ROUTES.MAIN,
  ADMIN_ROUTES.STAFFS.LIST,
  ADMIN_ROUTES.STAFFS.CREATE,
  ADMIN_ROUTES.STAFFS.DETAIL,
  // Đã xóa ADMIN_ROUTES.SETTINGS...

  // 3. Content Management (Main Dashboard)
  // Projects
  DASHBOARD_ROUTES.PROJECTS.LIST,
  DASHBOARD_ROUTES.PROJECTS.CREATE,
  DASHBOARD_ROUTES.PROJECTS.DETAIL,

  // Categories
  DASHBOARD_ROUTES.CATEGORIES.LIST,
  DASHBOARD_ROUTES.CATEGORIES.CREATE,
  DASHBOARD_ROUTES.CATEGORIES.DETAIL,

  // Blogs
  DASHBOARD_ROUTES.BLOGS.LIST,
  DASHBOARD_ROUTES.BLOGS.CREATE,
  DASHBOARD_ROUTES.BLOGS.DETAIL,

  // Blog Types
  DASHBOARD_ROUTES.BLOG_TYPES.LIST,
  DASHBOARD_ROUTES.BLOG_TYPES.CREATE,
  DASHBOARD_ROUTES.BLOG_TYPES.DETAIL,

  // Contacts
  DASHBOARD_ROUTES.CONTACTS.LIST,
  DASHBOARD_ROUTES.CONTACTS.DETAIL,
];